// Playable adaptation of the MIT-licensed Aetherfall design by Yoi-Nakama.
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),stats=document.getElementById('stats'),intro=document.getElementById('intro'),controls=document.getElementById('controls');
const W=1280,H=720,keys={};let running=false,last=0,gold=0,mana=100,hp=100,won=false;
const player={x:70,y:540,w:40,h:64,vx:0,vy:0,on:false,face:1,attack:0,magic:0};
const platforms=[{x:0,y:630,w:1280,h:90},{x:230,y:520,w:180,h:24},{x:500,y:445,w:170,h:24},{x:755,y:535,w:155,h:24},{x:990,y:425,w:170,h:24}];
let enemies,coins,bolts;
function reset(){hp=100;mana=100;gold=0;won=false;Object.assign(player,{x:70,y:540,vx:0,vy:0,attack:0,magic:0});enemies=[{x:340,y:572,w:45,h:58,hp:3,dir:1},{x:560,y:387,w:45,h:58,hp:3,dir:-1},{x:820,y:477,w:45,h:58,hp:4,dir:1},{x:1060,y:367,w:52,h:58,hp:5,dir:-1}];coins=[{x:280,y:480},{x:580,y:405},{x:800,y:495},{x:1080,y:385}];bolts=[];updateStats()}
function updateStats(){stats.textContent=`HP ${Math.max(0,Math.ceil(hp))} · MANA ${Math.floor(mana)} · GOLD ${gold}`}
function press(name,on){keys[name]=on;if(on&&name==='jump'&&player.on){player.vy=-720;player.on=false}if(on&&name==='attack')player.attack=.25;if(on&&name==='magic'&&mana>=20&&player.magic<=0){mana-=20;player.magic=.45;bolts.push({x:player.x+player.w/2,y:player.y+25,vx:player.face*620});updateStats()}}
document.querySelectorAll('#controls button').forEach(b=>{const n=b.dataset.key;b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture?.(e.pointerId);press(n,true)});['pointerup','pointercancel','pointerleave'].forEach(t=>b.addEventListener(t,()=>press(n,false)))});
addEventListener('keydown',e=>{const m={ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right',ArrowUp:'jump',w:'jump',' ':'attack',f:'magic'};if(m[e.key]){e.preventDefault();press(m[e.key],true)}if(e.key==='Escape')location.href='../arcade-launcher.html'});addEventListener('keyup',e=>{const m={ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right',ArrowUp:'jump',w:'jump',' ':'attack',f:'magic'};if(m[e.key])press(m[e.key],false)});
function overlap(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function update(dt){if(won)return;player.vx=((keys.right?1:0)-(keys.left?1:0))*310;if(player.vx)player.face=Math.sign(player.vx);player.vy+=1800*dt;player.x=Math.max(0,Math.min(W-player.w,player.x+player.vx*dt));let oldBottom=player.y+player.h;player.y+=player.vy*dt;player.on=false;for(const p of platforms){if(player.vy>=0&&oldBottom<=p.y&&player.y+player.h>=p.y&&player.x+player.w>p.x&&player.x<p.x+p.w){player.y=p.y-player.h;player.vy=0;player.on=true}}if(player.y>H){hp-=20;player.x=70;player.y=520;player.vy=0;updateStats()}player.attack=Math.max(0,player.attack-dt);player.magic=Math.max(0,player.magic-dt);mana=Math.min(100,mana+8*dt);for(const e of enemies){e.x+=e.dir*55*dt;if(e.x<30||e.x>1180)e.dir*=-1;if(player.attack>0){const blade={x:player.face>0?player.x+player.w:player.x-55,y:player.y+12,w:55,h:42};if(overlap(blade,e)&&!e.hit){e.hp--;e.hit=.25}}e.hit=Math.max(0,(e.hit||0)-dt);if(overlap(player,e)&&!e.hit){hp-=18*dt;if(hp<=0){reset();return}}}for(const b of bolts){b.x+=b.vx*dt;for(const e of enemies)if(e.hp>0&&overlap({x:b.x-8,y:b.y-8,w:16,h:16},e)){e.hp-=2;b.dead=true}}bolts=bolts.filter(b=>!b.dead&&b.x>0&&b.x<W);enemies=enemies.filter(e=>e.hp>0);coins=coins.filter(c=>{if(Math.hypot(player.x+20-c.x,player.y+30-c.y)<45){gold+=25;updateStats();return false}return true});if(player.x>1190&&enemies.length===0){won=true;setTimeout(()=>{intro.innerHTML='<h1>DUNGEON CLEARED</h1><h2>The portal is open</h2><p>You defeated the catacomb guardians and escaped with the treasure.</p><button id="again">Enter Again</button>';intro.classList.remove('hidden');document.getElementById('again').onclick=()=>{reset();intro.classList.add('hidden')}} ,400)}updateStats()}
function draw(){ctx.fillStyle='#090713';ctx.fillRect(0,0,W,H);let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#1d1230');g.addColorStop(1,'#07060c');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(let i=0;i<20;i++){ctx.fillStyle='#8a65aa22';ctx.fillRect((i*137)%W,80+(i*97)%480,80,8)}for(const p of platforms){ctx.fillStyle='#33273e';ctx.fillRect(p.x,p.y,p.w,p.h);ctx.fillStyle='#75538b';ctx.fillRect(p.x,p.y,p.w,5)}for(const c of coins){ctx.shadowBlur=18;ctx.shadowColor='#ffce62';ctx.fillStyle='#ffd66e';ctx.beginPath();ctx.arc(c.x,c.y,10,0,7);ctx.fill()}ctx.shadowBlur=0;for(const e of enemies){ctx.fillStyle=e.hit?'#fff':'#9d405d';ctx.fillRect(e.x,e.y,e.w,e.h);ctx.fillStyle='#ff8da7';ctx.fillRect(e.x+8,e.y+12,9,9);ctx.fillRect(e.x+28,e.y+12,9,9)}for(const b of bolts){ctx.shadowBlur=20;ctx.shadowColor='#4bdcff';ctx.fillStyle='#7be9ff';ctx.beginPath();ctx.arc(b.x,b.y,9,0,7);ctx.fill()}ctx.shadowBlur=0;ctx.fillStyle='#cbb0ed';ctx.fillRect(player.x,player.y,player.w,player.h);ctx.fillStyle='#f1d5bd';ctx.fillRect(player.x+9,player.y+5,22,20);ctx.fillStyle='#5b2f72';ctx.fillRect(player.x+5,player.y+28,30,36);if(player.attack>0){ctx.strokeStyle='#fff0a0';ctx.lineWidth=8;ctx.beginPath();ctx.arc(player.x+20,player.y+35,60,player.face>0?-1.1:2.1,player.face>0?1.1:4.2);ctx.stroke()}ctx.shadowBlur=28;ctx.shadowColor=enemies.length?'#8c4661':'#69f2ff';ctx.fillStyle=enemies.length?'#682e46':'#5ee9ff';ctx.fillRect(1210,510,32,120);ctx.shadowBlur=0;ctx.fillStyle='#eee';ctx.font='20px sans-serif';ctx.fillText(enemies.length?`Defeat ${enemies.length} guardian${enemies.length===1?'':'s'} to open the portal`:'Portal open!',920,670)}
function frame(t){let dt=Math.min(.03,(t-last)/1000||0);last=t;if(running)update(dt);draw();requestAnimationFrame(frame)}document.getElementById('begin').onclick=()=>{intro.classList.add('hidden');controls.classList.add('playing');running=true;last=performance.now()};document.getElementById('restart').onclick=reset;reset();requestAnimationFrame(frame);
