// Adapted from Neon Pong by knotasu, MIT licensed.
const canvas=document.getElementById('pongCanvas'),ctx=canvas.getContext('2d'),scoreEl=document.getElementById('score'),overlay=document.getElementById('message'),startBtn=document.getElementById('start'),pauseBtn=document.getElementById('pause');
const W=600,H=900;let playing=false,last=0,playerScore=0,cpuScore=0;
const player={x:220,y:842,w:160,h:20},cpu={x:220,y:38,w:160,h:20},ball={x:300,y:450,r:13,vx:250,vy:330};
function reset(dir=1){ball.x=W/2;ball.y=H/2;ball.vx=(Math.random()>.5?1:-1)*250;ball.vy=dir*330}
function movePlayer(clientX){const r=canvas.getBoundingClientRect();player.x=Math.max(0,Math.min(W-player.w,(clientX-r.left)/r.width*W-player.w/2))}
canvas.addEventListener('pointerdown',e=>{movePlayer(e.clientX);canvas.setPointerCapture?.(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(e.buttons||e.pointerType==='touch')movePlayer(e.clientX)});
addEventListener('keydown',e=>{if(e.key==='ArrowLeft')player.x=Math.max(0,player.x-45);if(e.key==='ArrowRight')player.x=Math.min(W-player.w,player.x+45);if(e.key==='Escape')location.href='../arcade-launcher.html'});
function update(dt){ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;if(ball.x-ball.r<0){ball.x=ball.r;ball.vx=Math.abs(ball.vx)}if(ball.x+ball.r>W){ball.x=W-ball.r;ball.vx=-Math.abs(ball.vx)}cpu.x+=((ball.x-cpu.w/2)-cpu.x)*Math.min(1,dt*5);cpu.x=Math.max(0,Math.min(W-cpu.w,cpu.x));if(ball.vy>0&&ball.y+ball.r>=player.y&&ball.y-ball.r<player.y+player.h&&ball.x>player.x&&ball.x<player.x+player.w){ball.y=player.y-ball.r;ball.vy=-Math.abs(ball.vy)*1.025;ball.vx+=(ball.x-(player.x+player.w/2))*3}if(ball.vy<0&&ball.y-ball.r<=cpu.y+cpu.h&&ball.y+ball.r>cpu.y&&ball.x>cpu.x&&ball.x<cpu.x+cpu.w){ball.y=cpu.y+cpu.h+ball.r;ball.vy=Math.abs(ball.vy)*1.018;ball.vx+=(ball.x-(cpu.x+cpu.w/2))*2.2}if(ball.y<-40){playerScore++;scoreEl.textContent=`YOU ${playerScore} · ${cpuScore} CPU`;reset(1)}if(ball.y>H+40){cpuScore++;scoreEl.textContent=`YOU ${playerScore} · ${cpuScore} CPU`;reset(-1)}}
function draw(){ctx.fillStyle='#040615';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#41e7ff33';ctx.lineWidth=4;ctx.setLineDash([18,20]);ctx.beginPath();ctx.moveTo(0,H/2);ctx.lineTo(W,H/2);ctx.stroke();ctx.setLineDash([]);for(let i=0;i<35;i++){ctx.fillStyle=i%3?'#798cff':'#ff5bc2';ctx.globalAlpha=.15+(i%5)*.08;ctx.fillRect((i*173)%W,(i*257)%H,3,3)}ctx.globalAlpha=1;ctx.shadowBlur=28;ctx.shadowColor='#ff42b1';ctx.fillStyle='#ff4db8';ctx.fillRect(cpu.x,cpu.y,cpu.w,cpu.h);ctx.shadowColor='#42f2ff';ctx.fillStyle='#58f5ff';ctx.fillRect(player.x,player.y,player.w,player.h);ctx.shadowColor='#fff';ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(ball.x,ball.y,ball.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}
function frame(t){const dt=Math.min(.03,(t-last)/1000||0);last=t;if(playing)update(dt);draw();requestAnimationFrame(frame)}
startBtn.onclick=()=>{overlay.classList.add('hidden');playing=true;last=performance.now()};pauseBtn.onclick=()=>{playing=!playing;pauseBtn.textContent=playing?'Pause':'Resume'};requestAnimationFrame(frame);
